MvcProje/Controllers/WriterPanelContentController.cs
using BusinessLayer.Concrete;
using DataAccessLayer.Concrete;
using DataAccessLayer.EntityFramework;
using EntityLayer.Concrete;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcProje.Controllers
{
    public class WriterPanelContentController : Controller
    {
        // GET: WriterPanelContent
        ContentManager cm = new ContentManager(new EfContentDal());

        Context c = new Context();
        public ActionResult MyContent(string p)
        {
            //int id=4;
            p = (string)Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == p).Select(y => y.WriterID).FirstOrDefault();
            //ViewBag.d = p;
            var contentvalues = cm.GetListByWriter(writeridinfo);
            return View(contentvalues);
        }
        [HttpGet]
        public ActionResult AddContent(int id)
        {
            ViewBag.d = id;
            return View();
        }
        [HttpPost]
        public ActionResult AddContent(Content p)
        {
            string mail = (string)Session["WriterMail"];
            var writeridinfo = c.Writers.Where(x => x.WriterMail == mail).Select(y => y.WriterID).FirstOrDefault();
            p.ContentDate = DateTime.Parse(DateTime.Now.ToShortDateString());
            p.WriterID = writeridinfo;
            p.ContentStatus = true;
            cm.ContentAdd(p);
            return RedirectToAction("MyContent");
        }
        public ActionResult ToDoList()
        {
            return View();
        }

    }
}

MvcProje/Views/WriterPanelContent/AddContent.cshtml
@model EntityLayer.Concrete.Content
@{
    ViewBag.Title = "AddContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}


<h1>İçerik Girişi</h1>
<br />
@using (Html.BeginForm("AddContent", "WriterPanelContent", FormMethod.Post))
{
    <div class="form-group">
        <br />
        <input type="hidden" name="HeadingID" value="@ViewBag.d"/>
        <br />
        @Html.Label("İçeriğinizi Yazın:")
        @Html.TextAreaFor(x => x.ContentValue,10,30, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.ContentValue)
        <br />

        <button class="btn btn-info">Kaydet</button>
    </div>
}

MvcProje/Views/WriterPanelContent/MyContent.cshtml
@using EntityLayer.Concrete
@model List<Content>
@{
    ViewBag.Title = "MyContent";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<!DOCTYPE html>
<html>
<body class="hold-transition sidebar-mini">
    <!-- Site wrapper -->
    <div class="wrapper">
        <section class="content">
            <div class="container-fluid">

                <!-- Timelime example  -->
                <div class="row">
                    <div class="col-md-12">
                        <!-- The time line -->
                        <div class="timeline">
                            <!-- timeline time label -->
                            @foreach (var item in Model)
                            {

                                <div class="time-label">
                                    <span class="bg-success">@(((DateTime)item.ContentDate).ToString("dd-MMM-yyyy"))</span>
                                </div>
                                <!-- /.timeline-label -->
                                <!-- timeline item -->
                                <div>
                                    <i class="fas fa-comment bg-yellow"></i>
                                    <div class="timeline-item">
                                        <h3 class="timeline-header"><a href="#">@item.Heading.HeadingName</a> </h3>
                                        <div class="timeline-body">
                                            @item.ContentValue
                                        </div>
                                    </div>
                                </div>
                                <!-- END timeline item -->

                            }
                        </div>
                    </div>
                    <!-- /.col -->
                </div>
            </div>
            <!-- /.timeline -->
        </section>
        <!-- /.content -->
    </div>
    <!-- ./wrapper -->
</body>
</html>

MvcProje/Views/WriterPanelContent/ToDoList.cshtml
@{
    ViewBag.Title = "ToDoList";
    Layout = "~/Views/Shared/_WriterLayout.cshtml";
}

<p1><del>#1 Profilim</del></p1>
<br />
<p1><del>#2 Tüm başlıklada paging</del></p1>
<br />
<p1><del>#3 MEsajlarda Session</del></p1>
<br />
<p1><del>#3 oturum yönetiminin mimariye taşınması</del> </p1>
<br />
<p1>#3 Token kullanımı </p1>
<br />


<h2>Admin yapılacaklar</h2>
<p1><del>#1 Başlıklara arama kutusu</del></p1>
<p1>Yazar GörselleriDüzenlenecek</p1>
<p1>Grafikler</p1>
<p1><del>Vitrin Teması</del></p1>
<p1>Gelen Kutusunda Arama--başlıklardakiyle aynı mantıkla yapabilirsin</p1> 
<p1>Yetkilendirme</p1>
<p1><del>hata Sayfası Layouttan Ayrılacak</del></p1>
<p1><del>Sözlük ve Vitrin Ayrılacak</del></p1>
<p1>Herhangibir tablo Raporlanacak</p1>
<p1>Proje Dosyaları sunucuya Taşınacak</p1>
<p1>Alan adı Alınacak</p1>
<p1>Proje Canlıya taşıanacak</p1>
<p1>Urlde ıd yerine isim gelsin</p1>
<p1><del>IFrameEkleme</del></p1>
<p1>Sweetalert</p1>
<p1>Admin Çıkış Yap</p1>